[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "py-algo-starter"
version = "0.1.0"
description = "Starter to fetch data, run Backtrader strategy and publish QuantStats report"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Marcelo Martini" }]
dependencies = [
  "pandas==2.2.2",
  "backtrader==1.9.78.123",
  "quantstats==0.0.62",
  "PyYAML>=6.0.1",
  "requests>=2.31.0",
]

[tool.hatch.build.targets.wheel]
packages = [{ include = "py_algo_starter", from = "src" }]
